baseURL = "https://joshsack.xyz/"
enableEmoji = true
languageCode = "en-us"
theme = "anatole"

[params]
    author = "Joshua Sack"
    contentratio = 0.75
    copyright = "Joshua Sack, 2021-{{ YEAR }}"
    description = "I am a PhD student in the economics at American University. My research interests include agent-based modeling and its applications to inequality, taxation, and cooperation. Before starting my degree, I worked on a number of Democratic campaigns as an opposition researcher. In my free time, I support Liverpool FC, and like to run long distances in very thin shoes."
    doNotLoadAnimations = false
    favicon = "favicons/"
    images = ["images/profile_pic.jpg"]
    indexDateFormat = "2006-01-02"
    mainSections = ["blog"]
    profilePicture = "images/profile.jpeg"
    readMore = true
    singleDateFormat = "2006-01-02"
    title = "Joshua Sack"

[[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/joshsack1"

[[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/Sack_Joshua"

[[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:jsack@joshsack.com"

[[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://linkedin.com/in/joshsack/"

[[params.socialIcons]]
    icon = "fab fa-mastodon"
    title = "Mastodon"
    url = "https://econtwitter.net/@Joshsack"

[[params.socialIcons]]
    icon = "fas fa-rss"
    title = "RSS"
    url = "https://www.joshsack.com/posts/index.xml"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "CV"
  weight = 7
  url = "/cv/"

[taxonomies]
tag = "tags"